stages:
  - build
  - test
  - docker_build

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - apt-get update -y
  - apt-get install -y docker.io

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:7.0
  script:
    - dotnet build --configuration Release
    - dotnet publish -c Release -o out

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:7.0
  script:
    - dotnet test --no-build --verbosity normal

docker_build:
  stage: docker_build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t myapp:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push myapp:latest
