using UTSATSAPI.Models.Generic;
using UTSATSAPI.Models.Models;
namespace UTSATSAPI.Repositories.Infrastructure.Repositories
{
public class PrgTempApplicationToolsMergePrgTalentApplicationToolRepository : GenericRepository<PrgTempApplicationToolsMergePrgTalentApplicationTool>, IPrgTempApplicationToolsMergePrgTalentApplicationToolRepository
{
public PrgTempApplicationToolsMergePrgTalentApplicationToolRepository(UTSATSAPIDBConnection dbContext) : base(dbContext){}
}
}
