using UTSATSAPI.Models.Generic;
using UTSATSAPI.Models.Models;
namespace UTSATSAPI.Repositories.Infrastructure.Repositories
{
public class PrgTempCertificationsMergePrgTalentCertificationRepository : GenericRepository<PrgTempCertificationsMergePrgTalentCertification>, IPrgTempCertificationsMergePrgTalentCertificationRepository
{
public PrgTempCertificationsMergePrgTalentCertificationRepository(UTSATSAPIDBConnection dbContext) : base(dbContext){}
}
}
