IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'RestoreChannels')
BEGIN
	CREATE TABLE dbo.RestoreChannels
	(
		ID BIGINT identity NOT NULL,
		HRID BIGINT NULL,
		ChannelID NVARCHAR(200) NULL,
		UserEmpID NVARCHAR(200) NULL,
		PerformAction NVARCHAR(MAX) NULL,
		ResponseStatus NVARCHAR(MAX) NULL,
		CreatedDT DATETIME DEFAULT GETDATE()
	)
END


